
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, ChevronDown, ChevronUp, Target, Flame, TrendingUp, Zap } from 'lucide-react';
import { FitnessPrediction } from '@/utils/mockData';

interface PredictionCardProps {
  prediction: FitnessPrediction;
}

const PredictionCard = ({ prediction }: PredictionCardProps) => {
  const [isExpanded, setIsExpanded] = useState(false);
  
  return (
    <Card className="shadow-sm overflow-hidden">
      <CardHeader className="pb-2 flex flex-row items-center justify-between space-y-0">
        <CardTitle className="text-xl font-semibold flex items-center">
          <Brain className="w-5 h-5 mr-2 text-fitness-primary" />
          AI Recommendations
        </CardTitle>
        <button 
          onClick={() => setIsExpanded(!isExpanded)}
          className="rounded-full p-1 hover:bg-gray-100 transition-colors"
          aria-label={isExpanded ? "Collapse" : "Expand"}
        >
          {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
        </button>
      </CardHeader>
      
      <CardContent className="pb-4">
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Target className="w-5 h-5 mr-2 text-fitness-primary" />
              <span className="text-sm font-medium">Next Goal</span>
            </div>
            <div className="bg-fitness-accent text-fitness-primary text-sm font-medium px-3 py-1 rounded-full">
              Short-term
            </div>
          </div>
          
          <div className="bg-gray-50 p-4 rounded-lg">
            <p className="text-gray-700">{prediction.nextGoal}</p>
          </div>
          
          <div className="flex items-center justify-between border-t border-dashed pt-4">
            <div className="flex items-center">
              <Flame className="w-5 h-5 mr-2 text-fitness-primary" />
              <span className="text-sm font-medium">Predicted Weight</span>
            </div>
            <div className="text-lg font-semibold">{prediction.predictedWeight} kg</div>
          </div>
          
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <TrendingUp className="w-5 h-5 mr-2 text-fitness-primary" />
              <span className="text-sm font-medium">Daily Calories</span>
            </div>
            <div className="text-lg font-semibold">{prediction.recommendedCalories} kcal</div>
          </div>
          
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Zap className="w-5 h-5 mr-2 text-fitness-primary" />
              <span className="text-sm font-medium">Fitness Score</span>
            </div>
            <div className="text-lg font-semibold">{prediction.fitnessScore}/100</div>
          </div>
          
          {isExpanded && (
            <div className="pt-2 space-y-4 animate-fade-in">
              <h4 className="text-sm font-medium flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 mr-2 text-fitness-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 20h9"></path>
                  <path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                </svg>
                Recommendations
              </h4>
              
              <div className="space-y-2">
                {prediction.recommendations.map((recommendation, index) => (
                  <div key={index} className="flex items-start">
                    <div className="bg-fitness-accent rounded-full w-6 h-6 flex items-center justify-center text-fitness-primary text-xs font-bold mr-3 mt-0.5 flex-shrink-0">
                      {index + 1}
                    </div>
                    <p className="text-gray-700">{recommendation}</p>
                  </div>
                ))}
              </div>
              
              <div className="pt-2 text-sm text-gray-500 italic border-t">
                These recommendations are generated by an AI model based on your fitness data and goals. Consult with a healthcare professional before making significant changes to your exercise or nutrition routine.
              </div>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};

export default PredictionCard;
